---
- name: Thao-test
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Check Memory Usage
      command: free
      register: print_memory_usage

    - debug:
        var: print_memory_usage.stdout_lines
