---
- name: Regex Processing for hostnames
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    eda_input: "{{ ipaddr.text }}"
    regex_pattern: '\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b'

  tasks:
    - name: Extract switch name from text
      set_fact:
       cacheable: yes
       machine: "{{ eda_input | regex_findall(regex_pattern) }}"
       regex_proc: done
    - name: debug
      debug:
        msg: "{{ machine }}"